# Generated by Django 3.1 on 2020-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200812_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='films.Genre'),
        ),
    ]
