# Generated by Django 3.1 on 2020-08-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_filmlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmList',
        ),
    ]
