# Generated by Django 3.1 on 2020-08-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_filmlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='date',
        ),
        migrations.AddField(
            model_name='film',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
