# Generated by Django 3.1 on 2020-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listname',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
