# Generated by Django 3.1 on 2020-08-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='film',
        ),
    ]
