# Generated by Django 3.1 on 2020-08-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_auto_20200812_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumb',
        ),
    ]
