# Generated by Django 3.1 on 2020-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0008_seenfilm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='Film',
            new_name='film',
        ),
    ]
